services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    container_name: connectifybackend
    env_file:
      - ./backend/.env
    networks:
      - connectify-network
    
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: connectifyfrontend
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    networks:
      - connectify-network


networks:
  connectify-network:
    driver: bridge
